[package]
name = "cli"
version = "0.1.0"
authors = ["Andy M <0andrewmartin0@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4.0.10"
subprocess = "0.1.18"
libloading = "0.6.2"
compiler = { path = "../compiler" }
