[package]
name = "regen_cli"
version = "0.1.0"
authors = ["Andy M <0andrewmartin0@gmail.com>"]
edition = "2018"

# [dev-dependencies]
# rusty-fork = "0.2.1"

[dependencies]
notify = "4.0.10"
subprocess = "0.1.18"
libloading = "0.6.2"
regen_core = { path = "../regen_core" }
